---
  #tasks file for roles/python
- name: Install latest python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Use pip3 as default pip
  shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

- name: Use python3 as default python
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10
